# Generated by Django 4.2.23 on 2025-11-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('isHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('isExpense', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tSum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tDateTime', models.DateTimeField(default=None, verbose_name='Date of transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from', to='finmanager.account')),
                ('accTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', to='finmanager.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('isExpense', models.BooleanField(default=True)),
                ('tDateTime', models.DateTimeField(default=None, verbose_name='Date of transaction')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finmanager.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finmanager.category')),
                ('checkID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finmanager.check')),
            ],
        ),
    ]
