# Generated by Django 5.1.7 on 2025-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sum',
        ),
        migrations.AddField(
            model_name='check',
            name='tDateTime',
            field=models.DateTimeField(default=None, verbose_name='Date of transaction'),
        ),
        migrations.AddField(
            model_name='check',
            name='tSum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tDateTime',
            field=models.DateTimeField(default=None, verbose_name='Date of transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tsum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
