# Generated by Django 4.2.20 on 2025-03-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0002_remove_check_sum_remove_transaction_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finmanager.check'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
