# Generated by Django 4.2.21 on 2025-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0003_alter_transaction_checkid_alter_transaction_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
