# Generated by Django 4.2.21 on 2025-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0005_transaction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='currBalance',
        ),
        migrations.AddField(
            model_name='account',
            name='startBalance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
