# Generated by Django 4.2.21 on 2025-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0006_rename_balance_account_currbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
