# Generated by Django 4.2.21 on 2025-05-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0007_account_ishidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currBalance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='startBalance',
        ),
    ]
