# Generated by Django 4.2.21 on 2025-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0008_rename_currbalance_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='startBalance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
