# Generated by Django 4.2.23 on 2025-06-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0009_account_startbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finmanager.account'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from', to='finmanager.account')),
                ('accTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', to='finmanager.account')),
            ],
        ),
    ]
